version: '3.8'

services:
  pulse:
    image: rcourtman/pulse:latest
    container_name: pulse-app
    restart: unless-stopped
    ports:
      - "7654:7654"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7654/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 