services:
  # Production service
  pulse:
    build:
      context: .
      target: production
      args:
        NODE_ENV: production
        LOG_LEVEL: info
        ENABLE_DEV_TOOLS: 'false'
        PORT: 7654
    container_name: pulse-app
    ports:
      - "7654:7654"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7654/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 