version: '3.8'

services:
  # Development service for testing
  pulse-test:
    build:
      context: .
      target: development
      args:
        NODE_ENV: development
        LOG_LEVEL: debug
        ENABLE_DEV_TOOLS: 'true'
        PORT: 3000
    ports:
      - "3002:3000"
    restart: unless-stopped
    env_file:
      - .env.test
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - ENABLE_DEV_TOOLS=true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 