services:
  pulse-app:
    image: rcourtman/pulse:latest
    container_name: pulse-app
    ports:
      - "7654:7654"
    env_file:
      - .env
    environment:
      - LOG_LEVEL=info
      - NODE_OPTIONS=--no-warnings
      - SUPPRESS_NO_CONFIG_WARNING=true
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: unless-stopped 