services:
  # Production service
  pulse:
    build:
      context: .
      target: production
      args:
        NODE_ENV: production
        LOG_LEVEL: info
        ENABLE_DEV_TOOLS: 'false'
        PORT: 7654
    ports:
      - "7654:7654"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7654/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Development service
  pulse-dev:
    build:
      context: .
      target: development
      args:
        NODE_ENV: development
        LOG_LEVEL: debug
        ENABLE_DEV_TOOLS: 'true'
        PORT: 7655
    ports:
      - "7655:7655"
      - "9513:9513"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/frontend/node_modules
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - ENABLE_DEV_TOOLS=true
      - PORT=7655
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7655/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 